---
Name: subsiteconfig
After:
  - 'framework/*'
---
SilverStripe\AssetAdmin\Controller\AssetAdmin:
  treats_subsite_0_as_global: true

SilverStripe\Control\Director:
  rules:
    SubsiteXHRController: SilverStripe\Subsites\Controller\SubsiteXHRController

SilverStripe\Reports\Report:
  excluded_reports:
    - SilverStripe\Subsites\Reports\SubsiteReportWrapper
